/*
 * Data Catalog Service - Asset Details
 *
 * API version: 1.0.0
 * Based on code Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"

	fybrikapi "fybrik.io/fybrik/pkg/model/datacatalog"
	api "github.com/fybrik/datacatalog-go/api"
)

type AtlasApiServicer interface {
	// CHANGE-FROM-GENERATED-CODE: replaced api.CreateAssetRequest with fybrikapi.CreateAssetRequest
	CreateAsset(context.Context, string, fybrikapi.CreateAssetRequest) (api.ImplResponse, error)

	DeleteAsset(context.Context, string, api.DeleteAssetRequest) (api.ImplResponse, error)
	GetAssetInfo(context.Context, string, api.GetAssetRequest) (api.ImplResponse, error)
	UpdateAsset(context.Context, string, api.UpdateAssetRequest) (api.ImplResponse, error)
}
