apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "atlas-connector.fullname" . }}
{{- if .Values.image.pullSecret }}
imagePullSecrets: 
  - name: {{ .Values.image.pullSecret }}
{{- end }}
